language: python
python:
- '3.4'
- '3.6'
install:
- |
  python -m venv venv
  ./venv/bin/python -m pip install -r requirements.txt
  cd src
script:
- "../venv/bin/python -m unittest discover test"
env:
  - secure: C0tN4Gnim2y1O3ulWSBygtIc7DfACAIgNC0F6Jj7MDrEJZjW8oMuWZLhkZHnuHDzz4zxgEPBl3BXfv0ydwkOO9SvihdmYhGTUiK/uyKGz/XngbjGKi7WIyAqXA3DeQHkxaJM3kNgpwpbCO3zUWgkn/XnSxFzH56rGAl42UuTfvNgBPMsTmyESphqmQ6n+SvTOZ2pAvIQBOeVgRCfUy3GUcb2ICfsvrVjqnJq6X2370TMgXpA+4OVX7r6mNpn+yfEYov73xEQ+eNapjY3hr6CQIoMFnG0ntXpiBf+nvO5MlokDE/2oRdbycSCeAQ7TB6kyCMAlIysIRJ7iaUL8NkHQHWpbqOlHXLVoOfehTDSbRF2wPaMp7+6ze8CAkGG6RqZds1JsbGPCD5aP2PD8wFiXPZb+UDF8HNitCqtACIXw0T5limlnO7x8HH4M5OxVaqZ8mOQ95OPH0EVusr66xjGIHS5oldFPGaRm7Z4ibpQ3mKH2+UKY9Ow+S91KAs5ptpRiIEcCfZP57jG+rbNyrBHTCuCrQV2AvArtyEGebB/QdpmVTYCAFrgWxEJY3fxWA0EyKXQbBwzxOZdsRvW5S+AkDLj5TqD7MZ8wPGrLpsTba9b1Zu9EwUy4Db7lL13VVrn5SPR+/Ct2OPtdsEokLgPmRQioT6eiz/bUmsmvCXOkxU=
  - secure: hTnzidyReyFIu5m7dwgwgJ5bhuB1Cu3HKnrZnT47Y8zvciYLF13jJW6FZlXj7XHueFzXFG0n5BrzJPCwWnDD6x/wqka3ZX4XLEJTCM1h04QXFt6vWx2gFrIzWPcm/KH/56RW2bUtldvAot/bSQ1mtvPlgI/5y8zs6ID2Bl+FwNw40/eaykEvmPtOgzeArJt7I1/OAwxXyt9o4FgH5n4XbnTsThXCGv1T1k+o5vl4A8tGjmGngIyKPEthEYRk3aji5iC8SW1n6mwwioz+14+Oy/2q0l7K76ODS0fRYpldJdIVuFz9PCRYk7QD/4cEkah0et2SDTAokLZhmrIZvsi0/zR4x1plm16Ujt0bA3T6+PwI7McwNn8PKOtv5++/v2zwPpljWmJ8J2jSWOJYfmbc/g9N2bOY7pbeQhEFeGcPcmmmaz9YmQj4H3/SD2cIdEb7JhCTuNafSGyNx212hY3uwZ1EKSU6KxiMvSn6kppTrc17WP8zGzfIiCT1yra4YcZ+DMDCvJsqytJs/MkUrmM5eQSjrckDdZZrP/e7rUEYzpr5q4zLZx2qviLFgavHhux7DLxd+WIpsLpSkzC+I52wXV9u6ZKxfTGnUxl0PQ7GYwyLm7fVME22zSbJKOAUp3E+9AEhnia6L9O18LADWQjCe1WG5aHDVh8FoUMqfcTxW7c=
