language: python
python:
    - '3.4'
    - '3.6'
install:
    - |
      python -m venv venv
      ./venv/bin/python -m pip install -r requirements.txt
      cd src
script:
    - "../venv/bin/python -m unittest discover test"
env:
  matrix:
  - secure: PCmX2tzv9ClYOsXa33WpiPBz1hK9PH5dyoneg3Tk4wEPEkstHddZYtaBiMRlb2IwibmHAt7puHycjRmT3W62vOKm7556TymEHmlZPomFFrQr46A/umMrUtjYfeEPUp08jwbysldRq2Xf/sI3p5s42CbulICFQFA4jgSRcu3OYink66jYqu+nsFI48E1zVc69Rhhb5vcFlFfeDvwgALpherMi8XwSOjf8ltXWM7lUuGz1WFuS+/RprDy3lzcBN+bXvuyFqpwqcSoooWjEXE5wvNN9hnhtUhwc5Dx0397X7H/Fzv2ynKDHkOEDk8Fg5kabeFHeTkELO7DWUl2AyJY9WtcwIUkWOwzZXHL6t90EvOG5yHSOoz6fFMGQAE4lokkECJ6Mts9F+hvkEhU7ashp7lWxZWacKaF3NC8bS/PbKuqxw5DQrRxiyx1HM7825ISX1WUYaf6j7oPaQ3lbo0LbgdDUPencmk8dGWmFt2OBOLtXnNxSf48am4uLUp6OYEIYjsangnhn7p+NMoIa1j4BYewbu3sTeVyXk4oEUI7emVUw4Ko5iLC5dT5ueBl5+Rcxk8kAa+dDU7oSWWdS33lSOeJ+DlGl/LPzKV0ywCE6R6+5JNH4eYLN1rbb8X3mts6F7Y5bYfgrLpooxz8G3C4aqg+xUHBuc8gsXf89rASDUzk=
  - secure: ic8qFdLa2L6Q5a/sOcnHlg9gI9JaehNhhWf9G8ybYucvAgRfWkobZj5m4XI4dtxNRePLqUufAFNNxvpnQij58G3s8zaumCf8B7QtxASqj6CGOLJ1gZ62ZnhowHuicUy4xbryxP7FShyzuNbeKQznCVdXRcjP5CI3nNPO90PS2yqftfVUG4DzqZuMbOfIodID2yUw/bY9IkwmVmnJuwpqS2m+xKqTp5Fa6l2RrcNNPnE4tdMujFFjxKTwBt2gkWOagEDPmdZlrxwVYAot4AWkbzNvIY7zjv7LG2/v11nrQgPIdfL09Tm46zvh2R7k3kI4RnFM8Z8GOz3EjyyzsEAk1uRu21/0LaXJqTXJ86LkokSpFL7RCiJxzrAEPTbV57IvyFEEwxAHkWaSLWUdu/1li+jSfGIQ8r52lOeU/oV3i+MDS2uur1V3tRFiDFTB/nIIurQqv6Coa1RnyOyM/3gt0lwtTOar7Xvn+U79/XfOCLR15Jntj1rR5SaaN7cnNsna8ig2fu4sDunxyVhgGGvK5DzfTxBDd/01Ggj5CypiIuTQNwLuzIBuTx9xIrft8aaxIy6nhRoz4U+TrU/JtqzJ+Hv+gzqNA46R5Jur0B7TBiaeb6+KWJf9zr/ZGF5YQiMaCqeVV3CI90niOiIGoawE6VGNh8E4Hd6usp5/Wqvj6Hc=
